### ISSUE TITLE
Add Extend Block to Request

### ISSUE THREAD

**Issue by kristijandraca** [johnhiott/DarkSkyApi#14]
for now I use this

    public class Request extends com.johnhiott.darkskyandroidlib.models.Request {
    private List<Block> mExtendBlocks = new ArrayList();
    @Override
    public Map<String, String> getQueryParams() {
        HashMap query = (HashMap) super.getQueryParams();
        query.put("extend", this.getExtendBlocks());
        return query;
    }
    private String getExtendBlocks() {
        return this.mExtendBlocks.size() > 0? Joiner.on(",").join(this.mExtendBlocks):null;
    }
    public void addExtendBlock(Request.Block exclude) {
        this.mExtendBlocks.add(exclude);
    }
    }

**Comment by johnhiott** [comment]
could you put together a merge request? :smile:

**Comment by kristijandraca** [comment]
Sure.
