### ISSUE TITLE
Checking if the callback has returned?

### ISSUE THREAD

**Issue by dp87** [johnhiott/DarkSkyApi#19]
First of all, thanks for the library, great job! This is really more of a question than an issue, but is there a way to check when the callback function has returned?

I am in a situation where I make a forecast request and I would like to send some weather data to a different fragment, but when my activity creates the fragment, the weather data has not returned yet so I am getting a bunch of null objects.

Or is there another way to do this?

**Comment by 0mega** [comment]
By now you probably figured out the answer, anyway, you can change the fragment in the callback response and only if the response code is 200 for e.g.
