### ISSUE TITLE
Apple has purchased Dark Sky and is shutting down the API

### ISSUE THREAD

**Issue by tinohager** [johnhiott/DarkSkyApi#30]
Apple has purchased Dark Sky and is shutting down the API.
The API will continue to function through the end of 2021.
[More Informations](https://blog.darksky.net/)

**Comment by iainfm** [comment]
I was wondering whether an easy 'fix' for this would be to use the openweather service. Apparently it has an matching api to dark sky, so *may* just be a case of changing a url somewhere. I'm going to investigate later...
