### ISSUE TITLE
Project not available on jitpack.io

### ISSUE THREAD

**Issue by Fl3W** [johnhiott/DarkSkyApi#31]
Atm apps that rely on that dependency cant be built anymore.

> Could not GET 'https://jitpack.io/com/github/johnhiott/DarkSkyApi/v0.1.5/DarkSkyApi-v0.1.5.pom'.
               > Read timed out

**Comment by johnhiott** [comment]
Hey!

Thanks for letting me know.
However, jitpack handles the distribution.  I am not sure why it would not be available but I have no control over it. I have not deleted any of the tags.

You can see what jitpack generates here:
https://jitpack.io/#johnhiott/DarkSkyApi

**Comment by johnhiott** [comment]
If jitpack continues to be a problem, I guess you could clone the repo and include it as a dependency locally.

**Comment by Fl3W** [comment]
Thanks for your answer. It should be back up and running, but if it doesn't at some point in the future I might have to. Yesterday I couldn't reach it via your link, but now it is available!
