### ISSUE TITLE
Minimum SDK version

### ISSUE THREAD

**Issue by flekken** [johnhiott/DarkSkyApi#8]
Could you set the minimum sdk to 9 or is there a reason to use 15 as minimum sdk?

**Comment by johnhiott** [comment]
Yeah. I'll make it as low as it can go. Sorry about that.

**Comment by johnhiott** [comment]
Retrofit and RxJava support version 2.3(9)+. I will make this change later today. 

Thanks for pointing that out!

**Comment by johnhiott** [comment]
closed with commit eb12b4196ec38b08f66166dfce5308014415ed1c

**Comment by johnhiott** [comment]
I went ahead a pushed a release just for that v0.1.2, updated readme
