### ISSUE TITLE
build issue on jitpack for 0.1.2

### ISSUE THREAD

**Issue by mediavrog** [johnhiott/DarkSkyApi#9]
Log https://jitpack.io/com/github/johnhiott/DarkSkyApi/v0.1.2/build.log

**Comment by johnhiott** [comment]
What exactly is your issue? I have no problem including the library using jitpack and building a project that uses it.

**Comment by johnhiott** [comment]
Plus that log file has a successful build

**Comment by mediavrog** [comment]
Interesting. When I opened that file today, there was a build error. I could also see on jitpack, that the build failed. But good if it is resolved now. You cannot access a history of recent build by any chance?

Anyway, good to see it working now.

**Comment by johnhiott** [comment]
I looked around a little on jitpack and did not see how to review old build files.
Maybe they had a problem yesterday.
Thanks for letting me know :)

**Comment by johnhiott** [comment]
closing for now because we cannot reproduce.
